services:
  shopco-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopco-backend:latest
    container_name: shopco-backend
    restart: unless-stopped
    networks:
      - traefik-net
    env_file:
      - .env # Load environment variables from .env file
    labels:
      - traefik.enable=true
      - traefik.http.routers.shopco-backend.rule=Host(`shopco-backend.${DOMAIN}`)
      - traefik.http.services.shopco-backend.loadbalancer.server.port=${PORT}
      - traefik.http.routers.shopco-backend.tls=true
      - traefik.http.routers.shopco-backend.entrypoints=websecure
      - traefik.http.routers.shopco-backend.tls.certresolver=cloudflare

networks:
  traefik-net:
    external: true
